"""Added VM Table

Revision ID: 59f9a3e5eb0d
Revises: 
Create Date: 2021-11-15 22:12:02.806804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f9a3e5eb0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('node', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_machine_name'), 'virtual_machine', ['name'], unique=False)
    op.create_index(op.f('ix_virtual_machine_vm_id'), 'virtual_machine', ['vm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_machine_vm_id'), table_name='virtual_machine')
    op.drop_index(op.f('ix_virtual_machine_name'), table_name='virtual_machine')
    op.drop_table('virtual_machine')
    # ### end Alembic commands ###
