"""empty message

Revision ID: ff9e82bb0352
Revises: c21dc0d9a025
Create Date: 2021-11-19 12:21:57.898023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9e82bb0352'
down_revision = 'c21dc0d9a025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machine', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_machine', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machine', type_='foreignkey')
    op.drop_column('virtual_machine', 'creator')
    # ### end Alembic commands ###
